import {
  ButtonSchema,
  ColumnSchema,
  ContainerSchema,
  HeadingSchema,
  HrSchema,
  ImgSchema,
  RowSchema,
  TextSchema,
} from "@/components/editor/elements";

import { z } from "zod";

// Define element schemas
const ElementSchema = z.discriminatedUnion("type", [
  z.object({
    ...ButtonSchema.shape,
  }),
  z.object({
    ...HeadingSchema.shape,
  }),
  z.object({
    ...HrSchema.shape,
  }),
  z.object({
    ...ImgSchema.shape,
  }),
  z.object({
    ...TextSchema.shape,
    children: z.array(z.string()).optional(),
  }),
]);

export type ElementType = z.infer<typeof ElementSchema>;

// Column with children
export const ColumnWithChildrenSchema = ColumnSchema.extend({
  id: z.string(),
  type: z.literal("column"),
  children: z.array(ElementSchema),
});

export type ColumnWithChildrenType = z.infer<typeof ColumnWithChildrenSchema>;

// Row with children
export const RowWithChildrenSchema = RowSchema.extend({
  id: z.string(),
  type: z.literal("row"),
  children: z.array(ColumnWithChildrenSchema),
});

export type RowWithChildrenType = z.infer<typeof RowWithChildrenSchema>;

// Container with children
const ContainerWithChildrenSchema = ContainerSchema.extend({
  type: z.literal("container"),
  children: z.array(RowWithChildrenSchema),
});

// Font schema
const FontSchema = z.object({
  family: z.string().optional().default("Arial"),
  fallback: z.array(z.string()).optional().default(["Helvetica", "sans-serif"]),
  weight: z.array(z.number()).optional().default([400, 700]),
});

// Main template schema
export const TemplateSchema = z.object({
  title: z.string(),
  preview: z.string(),
  font: FontSchema,
  container: ContainerWithChildrenSchema,
});

export type TemplateSchemaType = z.infer<typeof TemplateSchema>;

// Example template with default values
export const defaultTemplate1: TemplateSchemaType = {
  title: "Resend Product Updates",
  preview: "Latest features and improvements from Resend",
  font: {
    family: "Inter",
    fallback: ["Helvetica", "sans-serif"],
    weight: [400, 500, 600, 700],
  },
  container: {
    id: "container-1",
    type: "container",
    backgroundColor: "#ffffff",
    width: "600px",
    height: "auto",
    horizontalPadding: 32,
    verticalPadding: 32,
    borderRadius: 8,
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderStyle: "solid",
    children: [
      {
        id: "row-logo",
        type: "row",
        title: "Logo",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 0,
        children: [
          {
            id: "col-logo",
            type: "column",
            title: "Logo Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "logo",
                type: "image",
                src: "https://resend.com/static/logo-dark.svg",
                title: "Resend Logo",
                width: "120px",
                height: "auto",
                align: "left",
                shape: "square",
                spacing: 0,
              },
            ],
          },
        ],
      },
      {
        id: "row-intro",
        type: "row",
        title: "Intro Section",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 48,
        children: [
          {
            id: "col-intro",
            type: "column",
            title: "Intro Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "intro-heading",
                type: "heading",
                title: "Main Heading",
                as: "h1",
                text: "Latest from Resend",
                color: "#000000",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.2,
                fontWeight: "600",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
              },
            ],
          },
        ],
      },
      {
        id: "row-update-1",
        type: "row",
        title: "Update 1",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 24,
        children: [
          {
            id: "col-update-1",
            type: "column",
            title: "Update 1 Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "update-1-image",
                type: "image",
                src: "https://resend.com/static/posts/react-email-v2.png",
                title: "React Email 2.0",
                width: "100%",
                height: "auto",
                align: "left",
                shape: "rounded",
                spacing: 24,
              },
              {
                id: "update-1-heading",
                type: "heading",
                title: "React Email Update",
                as: "h2",
                text: "React Email 2.0",
                color: "#000000",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "update-1-text",
                type: "text",
                title: "React Email Description",
                html: "We're excited to announce React Email 2.0. Build and send emails using React components with improved performance, better developer experience, and new features.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-update-2",
        type: "row",
        title: "Update 2",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 24,
        children: [
          {
            id: "col-update-2",
            type: "column",
            title: "Update 2 Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "update-2-image",
                type: "image",
                src: "https://resend.com/static/posts/email-analytics.png",
                title: "Email Analytics",
                width: "100%",
                height: "auto",
                align: "left",
                shape: "rounded",
                spacing: 24,
              },
              {
                id: "update-2-heading",
                type: "heading",
                title: "Introducing Email Analytics",
                as: "h2",
                text: "Introducing Email Analytics",
                color: "#000000",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "update-2-text",
                type: "text",
                title: "Mobile Order Description",
                html: "Track email performance with comprehensive analytics. Monitor opens, clicks, and deliverability in real-time with our new analytics dashboard.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-update-3",
        type: "row",
        title: "Update 3",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 24,
        children: [
          {
            id: "col-update-3",
            type: "column",
            title: "Update 3 Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "update-3-image",
                type: "image",
                src: "https://resend.com/static/posts/api-reference.png",
                title: "API Improvements",
                width: "100%",
                height: "auto",
                align: "left",
                shape: "rounded",
                spacing: 24,
              },
              {
                id: "update-3-heading",
                type: "heading",
                title: "New API Reference",
                as: "h2",
                text: "New API Reference",
                color: "#000000",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "update-3-text",
                type: "text",
                title: "API Improvements Description",
                html: "We've revamped our API documentation with improved navigation, better examples, and comprehensive guides to help you integrate Resend faster.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-cta",
        type: "row",
        title: "CTA Section",
        columns: "100",
        gap: 0,
        backgroundColor: "#f9fafb",
        horizontalPadding: 24,
        verticalPadding: 24,
        children: [
          {
            id: "col-cta",
            type: "column",
            title: "CTA Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "cta-text",
                type: "text",
                title: "CTA Text",
                html: "<span style='color: #ffffff;'>Ready to redeem your Stars?</span>",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.5,
                fontWeight: "500",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "center",
                fontSize: "18px",
              },
              {
                id: "cta-button",
                type: "button",
                title: "CTA Button",
                text: "Get started",
                fontFamily: "Inter, Helvetica, sans-serif",
                href: "https://resend.com",
                align: "left",
                width: "120px",
                height: 10,
                horizontalMargin: 16,
                verticalMargin: 16,
                backgroundColor: "#000000",
                color: "#ffffff",
                fontSize: "14px",
                borderRadius: 6,
              },
            ],
          },
        ],
      },
      {
        id: "row-footer",
        type: "row",
        title: "Footer",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 32,
        children: [
          {
            id: "col-footer",
            type: "column",
            title: "Footer Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "footer-text",
                type: "text",
                title: "Footer Text",
                html: "© 2024 Resend. All rights reserved.<br><a href='#' style='color: #6b7280; text-decoration: underline;'>Unsubscribe</a>",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "Inter, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "14px",
              },
            ],
          },
        ],
      },
    ],
  },
};

export const defaultTemplate: TemplateSchemaType = {
  title: "Starbucks Rewards Update",
  preview: "See your Stars balance and exclusive offers",
  font: {
    family: "SoDo Sans",
    fallback: ["Helvetica", "Arial", "sans-serif"],
    weight: [400, 500, 600, 700],
  },
  container: {
    id: "container-1",
    type: "container",
    backgroundColor: "#ffffff",
    width: "600px",
    height: "auto",
    horizontalPadding: 32,
    verticalPadding: 32,
    borderRadius: 8,
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderStyle: "solid",
    children: [
      {
        id: "row-logo",
        type: "row",
        title: "Logo",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 0,
        children: [
          {
            id: "col-logo",
            type: "column",
            title: "Logo Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "logo",
                type: "image",
                src: "https://logodownload.org/wp-content/uploads/2017/10/Starbucks-logo.png",
                title: "Starbucks Logo",
                width: "80px",
                height: "auto",
                align: "left",
                shape: "square",
                spacing: 0,
              },
            ],
          },
        ],
      },
      {
        id: "row-intro",
        type: "row",
        title: "Intro Section",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 48,
        children: [
          {
            id: "col-intro",
            type: "column",
            title: "Intro Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "intro-heading",
                type: "heading",
                title: "Main Heading",
                as: "h1",
                text: "Your Starbucks Rewards Update",
                color: "#1e3932",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.2,
                fontWeight: "700",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "intro-text",
                type: "text",
                title: "Intro Text",
                html: "Hi [Name], here's your latest Rewards status and exclusive offers just for you!",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "16px",
              },
            ],
          },
        ],
      },
      {
        id: "row-stars-balance",
        type: "row",
        title: "Stars Balance",
        columns: "100",
        gap: 0,
        backgroundColor: "#f1f8f6",
        horizontalPadding: 24,
        verticalPadding: 24,
        children: [
          {
            id: "col-stars",
            type: "column",
            title: "Stars Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "8px",
            children: [
              {
                id: "stars-heading",
                type: "heading",
                title: "Stars Balance Heading",
                as: "h2",
                text: "⭐ 275 Stars",
                color: "#1e3932",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "stars-text",
                type: "text",
                title: "Stars Description",
                html: "You're only 25 Stars away from your next free drink! Visit us today to earn more Stars.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-offer-1",
        type: "row",
        title: "Special Offer 1",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 32,
        children: [
          {
            id: "col-offer-1",
            type: "column",
            title: "Offer 1 Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "offer-1-image",
                type: "image",
                src: "https://elmhurst1925.com/cdn/shop/files/PumpkinSpiceLatte_1920x1080_e302c85a-4609-4aeb-af95-eec1927b6a3d.jpg?v=2999713701403906626",
                title: "Pumpkin Spice Latte",
                width: "100%",
                height: "auto",
                align: "left",
                shape: "rounded",
                spacing: 24,
              },
              {
                id: "offer-1-heading",
                type: "heading",
                title: "Offer 1 Heading",
                as: "h2",
                text: "Double Stars on Seasonal Favorites",
                color: "#1e3932",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "offer-1-text",
                type: "text",
                title: "Offer 1 Description",
                html: "Earn 2x Stars when you order any seasonal beverage between 2-5 PM. Valid through October 31st.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-offer-2",
        type: "row",
        title: "Special Offer 2",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 32,
        children: [
          {
            id: "col-offer-2",
            type: "column",
            title: "Offer 2 Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "offer-2-image",
                type: "image",
                src: "https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/9d3b3793-40ae-4d00-815c-bd809e8a3898/image.png?t=1692298412",
                title: "Mobile Order",
                width: "100%",
                height: "auto",
                align: "left",
                shape: "rounded",
                spacing: 24,
              },
              {
                id: "offer-2-heading",
                type: "heading",
                title: "Offer 2 Heading",
                as: "h2",
                text: "Skip the Line with Mobile Order",
                color: "#1e3932",
                horizontalPadding: 0,
                verticalPadding: 0,
                horizontalMargin: 0,
                verticalMargin: 16,
                lineHeight: 1.4,
                fontWeight: "600",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
              },
              {
                id: "offer-2-text",
                type: "text",
                title: "Offer 2 Description",
                html: "Order ahead and earn an extra 25 Bonus Stars on your next mobile order over $15.",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "left",
                fontSize: "15px",
              },
            ],
          },
        ],
      },
      {
        id: "row-cta",
        type: "row",
        title: "CTA Section",
        columns: "100",
        gap: 0,
        backgroundColor: "#1e3932",
        horizontalPadding: 24,
        verticalPadding: 24,
        children: [
          {
            id: "col-cta",
            type: "column",
            title: "CTA Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "cta-text",
                type: "text",
                title: "CTA Text",
                html: "<span style='color: #ffffff;'>Ready to redeem your Stars?</span>",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.5,
                fontWeight: "500",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "center",
                fontSize: "18px",
              },
              {
                id: "cta-button",
                type: "button",
                title: "CTA Button",
                text: "Order Now",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                href: "https://www.starbucks.com/rewards",
                align: "center",
                width: "200px",
                height: 12,
                horizontalMargin: 16,
                verticalMargin: 16,
                backgroundColor: "#00754a",
                color: "#ffffff",
                fontSize: "16px",
                borderRadius: 24,
              },
            ],
          },
        ],
      },
      {
        id: "row-footer",
        type: "row",
        title: "Footer",
        columns: "100",
        gap: 0,
        backgroundColor: "transparent",
        horizontalPadding: 0,
        verticalPadding: 32,
        children: [
          {
            id: "col-footer",
            type: "column",
            title: "Footer Column",
            width: "100%",
            backgroundColor: "transparent",
            horizontalPadding: 0,
            verticalPadding: 0,
            borderRadius: "0px",
            children: [
              {
                id: "footer-text",
                type: "text",
                title: "Footer Text",
                html: "© 2024 Starbucks Coffee Company. All rights reserved.<br>This email was sent to you as a Starbucks Rewards member.<br><a href='#' style='color: #00754a; text-decoration: underline;'>Manage Preferences</a> | <a href='#' style='color: #00754a; text-decoration: underline;'>Unsubscribe</a>",
                horizontalPadding: 0,
                verticalPadding: 0,
                lineHeight: 1.6,
                fontWeight: "400",
                fontFamily: "SoDo Sans, Helvetica, sans-serif",
                textAlign: "center",
                fontSize: "14px",
              },
            ],
          },
        ],
      },
    ],
  },
};
